cmake_minimum_required(VERSION 3.20)
if(NOT IS_DIRECTORY "${APP_DIR}" OR NOT EXISTS "${RUNTIME}/astracore-runtime.json")
    message(FATAL_ERROR "Existing app directory and complete AstraCore runtime required")
endif()
file(REAL_PATH "${APP_DIR}" app_root)
file(REAL_PATH "${APP_DIR}/assets/bin" destination)
cmake_path(IS_PREFIX app_root "${destination}" NORMALIZE inside_app)
if(NOT inside_app OR destination STREQUAL app_root)
    message(FATAL_ERROR "Media deployment directory escapes the application: ${destination}")
endif()
# This directory is the media payload. Remove previous ABI versions before
# copying the complete upstream runtime, including ffprobe/libmpv/licenses.
file(REMOVE_RECURSE "${destination}")
file(MAKE_DIRECTORY "${destination}")
file(COPY "${RUNTIME}/" DESTINATION "${destination}")
file(REMOVE "${app_root}/AstraCore.Native.dll")
file(READ "${RUNTIME}/astracore-runtime.json" manifest)
string(JSON count LENGTH "${manifest}" files)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON path GET "${manifest}" files ${index} path)
    string(JSON expected GET "${manifest}" files ${index} sha256)
    file(SHA256 "${destination}/${path}" actual)
    string(TOUPPER "${actual}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Deployed runtime file hash mismatch: ${path}")
    endif()
endforeach()
message(STATUS "Deployed and verified all ${count} upstream AstraCore runtime files")
