set(_astra_package "${CMAKE_CURRENT_SOURCE_DIR}/third_party/astracore_windows")
file(READ "${_astra_package}/archive.json" _astra_archive_info)
string(JSON _astra_revision GET "${_astra_archive_info}" revision)
string(JSON _astra_hash GET "${_astra_archive_info}" sha256)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/third_party/astracore/upstream-revision.txt" _astra_source_revision)
string(STRIP "${_astra_source_revision}" _astra_source_revision)
if(NOT _astra_source_revision STREQUAL _astra_revision)
    message(FATAL_ERROR "Windows AstraCore runtime must be refreshed with the pinned source revision")
endif()
file(SHA256 "${_astra_package}/AstraCore-win-x64.zip" _astra_actual_hash)
if(NOT _astra_actual_hash STREQUAL _astra_hash)
    message(FATAL_ERROR "Windows AstraCore archive SHA256 mismatch")
endif()
set(AEGISUB_BUNDLED_ASTRA_RUNTIME "${CMAKE_BINARY_DIR}/_deps/astracore-${_astra_hash}")
file(ARCHIVE_EXTRACT INPUT "${_astra_package}/AstraCore-win-x64.zip"
    DESTINATION "${AEGISUB_BUNDLED_ASTRA_RUNTIME}")
message(STATUS "Using complete verified Windows AstraCore runtime ${_astra_revision}")
